databases:
  - name: edgesignal-db
    plan: free
    databaseName: edgesignal
    user: edgesignal

services:
  - type: web
    name: edgesignal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EDGESIGNAL_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: edgesignal-db
          property: connectionString
